# **DACON - 퇴근시간 버스승차인원 예측 경진대회 연습**
- 공공 교통 위치 빅데이터와 AI로 버스 승객 이용 분석
- 회귀, RMSE

## **data**

* (train, test , bus_bts) 공통 사항

해당 데이터에는 버스카드를 통해 결제를 한 경우에 대한 정류소 승, 하차 데이터로 모든 승차정보의 경우는 기록이 되어있지만, 

버스에서 하차를 할 때, 버스카드를 찍지 않는 경우, 해당 기록이 비어 있는 상태입니다. 따라서, 승차 인원수와 하차 인원수가 동일하지 않고 다소 차이가 있음을 미리 알려드립니다.

* (train, test csv) 공통사항

해당 버스정류장에 대한 각각의 위도, 경도가 제공이 되어있는 상태로 같은 정류장 이름이지만 위도와 경도가 서로 다른 경우가 존재합니다. 

해당 경우는, 같은 정류장 이름을 가지고 있는 길 건너편의 정류장에 해당이 됩니다.

 



1. **train.csv and test.csv**

 

train.csv 의 경우, 2019년 9월 제주도의 각 날짜, 출근시간(6시~12시)의 버스 정류장별 승하차 인원, 퇴근시간(18시~20시)의 버스 정류장별 승차 인원이 기록되어 있습니다.

test.csv의 경우, 2019년 10월의 각 날짜, 출근시간(오전 6시~12시)의 버스 정류장별 승하차 인원이 기록되어 있습니다.



2. **bus_bts.csv**

 

bus_bts의 경우, 버스카드별로 승하차 정보가 기록이 되어있습니다. 해당 데이터는 탑승 시간대가오전 6시부터 12시 사이인 경우만 있습니다.



3. **submission_제출양식.csv**

 

submission_제출양식의 경우, test data의 ID와 목표변수인 18시~20시 승차 인원로만 이루어져 있습니다.

참가자분들께서는 test.csv에서 ID와 예측값을 결합하여, 해당 submission_제출양식.csv 파일형식 처럼 만든 이후,

해당 제출 파일 양식 그대로(변수명 포함된 상태) 제출을 해주시면 됩니다



추가 사용 가능 데이터

      a) (8회 kcb 시각화 대회의 제주도 금융라이프 데이터(jeju_financial_life_data.csv)

      b) 행정동별 위도 경도 데이터 https://dacon.io/?module=file&act=procFileDownload&file_srl=244977&sid=8cd192144ab18be0e02e4a16f851729b&module_srl=228539  (H - 행정동, B - 법정동)

In [13]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=False)

Mounted at /content/gdrive

In [18]:
import zipfile
         
with zipfile.ZipFile('/content/gdrive/My Drive/Colab Notebooks/DACON/data/data13.zip') as existing_zip:
  existing_zip.extractall()

In [19]:
import pandas as pd

train_df = pd.read_csv('train.csv') 
train_df.head(3)

   id        date  bus_route_id  ... 10~11_takeoff  11~12_takeoff 18~20_ride
0   0  2019-09-01       4270000  ...           0.0            0.0        0.0
1   1  2019-09-01       4270000  ...           0.0            0.0        5.0
2   2  2019-09-01       4270000  ...           0.0            0.0        2.0

[3 rows x 21 columns]